# COSC 3337 Lab 01 Minh Nguyen

Import numpy

In [1]:
import numpy as np
python_list = [1,2,3,4,5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


Python list

In [2]:
python_list = [1,3,4, 4, 6,1, 2]
print(python_list)
print(type(python_list))

[1, 3, 4, 4, 6, 1, 2]
<class 'list'>


numpy array function

In [3]:
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 3 4 4 6 1 2]
<class 'numpy.ndarray'>


2D array

In [4]:
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


2D array with numpy

In [5]:
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


Not a 2D array

In [6]:
python_2d_array_test = [[1,2,3],[1,2],[1,3,4,5]]
numpy_2d_array_test = np.array(python_2d_array_test)
print(numpy_2d_array_test)
print(type(numpy_2d_array_test))

[list([1, 2, 3]) list([1, 2]) list([1, 3, 4, 5])]
<class 'numpy.ndarray'>


/var/folders/b5/174qqshj3px_y32r11qg8td40000gn/T/ipykernel_42021/1734345002.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  numpy_2d_array_test = np.array(python_2d_array_test)


numpy arange

In [7]:
arange1 = np.arange(0,20)
arange1_1 = np.arange(0,20,1)
print('arange1: ', arange1)
print('arange1_1: ', arange1_1)

arange1:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arange1_1:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy arange with step size

In [8]:
arange2 = np.arange(0,10,2)
arange2_1 = np.arange(0,2,10)
print('arange2: ', arange2)
print('arange2_1: ', arange2_1)

arange2:  [0 2 4 6 8]
arange2_1:  [0]


numpy arange 2d array

In [9]:
numpy_2d_arange_array = np.arange(0, 15).reshape(3, 5)
numpy_2d_arange_array_test = np.arange(0, 20).reshape(4, 5)
print('numpy_2d_arange_array: ', numpy_2d_arange_array)
print('numpy_2d_arange_array_test: ', numpy_2d_arange_array_test)

numpy_2d_arange_array:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
numpy_2d_arange_array_test:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


ndarray of zeroes or ones

In [10]:
zeros_np = np.zeros(10)
zeros_np_reshape1 = np.zeros(10).reshape(2,5)
ones_np_reshape2 = np.ones(15).reshape(5,3)
print('zeros_np: ', zeros_np)
print('zeros_np_reshape1: ', zeros_np_reshape1)
print('ones_np_reshape2: ', ones_np_reshape2)

zeros_np:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeros_np_reshape1:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones_np_reshape2:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype=int

In [11]:
np.ones(24, dtype=int).reshape(4, 6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

identity matrix

In [12]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

generate an ndarray of random numbers

In [13]:
print(np.random.rand(5))
print(np.random.randn(5))
print(np.random.randint(10,200))
print(np.random.randint(1, 10, 15))
A = np.random.randint(0, 20, 20).reshape(4, 5)
print('A: ', A)
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')
print('Shape: ', np.shape(A))

[0.63221983 0.08007579 0.58438305 0.68834122 0.96817547]
[-0.53335323  0.14359853  1.05872005  0.45623498 -0.24742821]
53
[1 3 8 9 3 5 6 7 7 3 1 1 7 2 3]
A:  [[ 5  5  2 19  0]
 [ 9  1  1 16  9]
 [ 2 19 15 10 11]
 [ 3  3  9  6  4]]
The smallest value in A is 0, and is a located at position 4
The largest value in A is 19, and is a located at position 3
Shape:  (4, 5)


Common Operations

In [14]:
A = np.arange(1, 10)
B = np.arange(1, 19, 2)
C = np.arange(0, 8).reshape(2, 4)
D = np.arange(0, 8).reshape(4, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print(f'C: \n{C}')
print(f'D: \n{D}')
print(f'E: \n{E}')
print(f'F: {F}')

A: [1 2 3 4 5 6 7 8 9]
B: [ 1  3  5  7  9 11 13 15 17]
C: 
[[0 1 2 3]
 [4 5 6 7]]
D: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
E: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


Arithmetic

In [15]:
print(f'A+B: {A+B}')
print(f'B-A: {B-A}')
print(f'A+3: {A+3}')
print(f'A*B: {A*B}')
print(f'B/A: {B/A}')
print(f'A%B: {A%B}')
print(f'C(2x4) * D(4x2): \n{np.matmul(C, D)}')


A+B: [ 2  5  8 11 14 17 20 23 26]
B-A: [0 1 2 3 4 5 6 7 8]
A+3: [ 4  5  6  7  8  9 10 11 12]
A*B: [  1   6  15  28  45  66  91 120 153]
B/A: [1.         1.5        1.66666667 1.75       1.8        1.83333333
 1.85714286 1.875      1.88888889]
A%B: [0 2 3 4 5 6 7 8 9]
C(2x4) * D(4x2): 
[[28 34]
 [76 98]]


Universal Functions

In [16]:
print('---- Universal Functions ----')
print(f'sqrt(E): {np.sqrt(E)}')
print(f'log(E): {np.log(E)}')
print(f'where() example: {np.where(F%2!=0, -2, F*20)}')

---- Universal Functions ----
sqrt(E): [[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]]
log(E): [[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]]
where() example: [  0  -2  40  -2  80  -2 120  -2 160  -2 200]


Indexing

In [17]:
# Indexing 1d array
print('---- Indexing 1d array ----')
A = np.arange(11)
print(f'A: {A}')
# Obtain a single element
print('---- Obtain a single element ----')
print(f'A[0]: {A[0]}')
print(f'A[4]: {A[4]}')
print(f'A[10]: {A[10]}')
# Grab a section of the array
print('---- Grab a section ----')
print(f'A[5] - A[10]: {A[5:11]}')
# Modify values in the array
print('---- Modify values in the array ----')
A[3:9] = 100
print(f'Modified A: {A}')

---- Indexing 1d array ----
A: [ 0  1  2  3  4  5  6  7  8  9 10]
---- Obtain a single element ----
A[0]: 0
A[4]: 4
A[10]: 10
---- Grab a section ----
A[5] - A[10]: [ 5  6  7  8  9 10]
---- Modify values in the array ----
Modified A: [  0   1   2 100 100 100 100 100 100   9  10]


In [18]:
# Indexing a 2d array
print('---- Indexing a 2d array ----')
B = np.arange(30).reshape(5, 6)
print(f'B: {B}')
# Obtain a single element
print('---- Obtain a single element ----')
print(f'0th row and 5th col in B: {B[0, 5]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 1st col in B: {B[4, 1]}')
#  Grab a section of the array
print('---- Grab a section of the array ----')
print(B[0:3, 3:6])
# Modify the values of the array
print('---- Modify the values of the array ----')
B[0:3, 3:6] = 200
print(f'Modified B: {B}')

---- Indexing a 2d array ----
B: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
---- Obtain a single element ----
0th row and 5th col in B: 5
3rd row and 3rd col in B: 21
4th row and 1st col in B: 25
---- Grab a section of the array ----
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]
---- Modify the values of the array ----
Modified B: [[  0   1   2 200 200 200]
 [  6   7   8 200 200 200]
 [ 12  13  14 200 200 200]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]]


In [19]:
# Boolean Array Indexing
print('---- Boolean Array Indexing ----')
C = np.arange(35).reshape(5, 7)
print(f'C: {C}')
# Indexing using comparison operators
print('---- Indexing using comparison operators ----')
# print(f'Indexes with condition C%2 == 0: \n{np.where(C%2 == 0,True,False)}')
print(f'C with odd number condition: \n{C%2 != 0}')
# sum function with condition
print('---- Sum function with condition ----')
print(f'Total number of odd numbers in C: {(C%2 != 0).sum()}')
print(f'Total number of even numbers in C: {(C%2 == 0).sum()}')
# Filter elements with condition
print('---- Filter elements with condition ----')
print(f'Filter out odd numbers from C: {C[C%2 != 0]}')

---- Boolean Array Indexing ----
C: [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
---- Indexing using comparison operators ----
C with odd number condition: 
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]
---- Sum function with condition ----
Total number of odd numbers in C: 17
Total number of even numbers in C: 18
---- Filter elements with condition ----
Filter out odd numbers from C: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
